project:
  type: website
  output-dir: _site

website:
  site-url: https://jamrbaserunningscience.netlify.app 
  title: "José Antonio Martínez-Rodríguez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: articles.qmd
        text: Articles
      - href: notes.qmd
        text: Notes
      - href: updates.qmd
        text: Updates
      - href: contact.qmd
        text: Contact
  page-footer:
    center:
      - icon: instagram
        href: https://instagram.com/jamrcat/
      - icon: linkedin
        href: https://linkedin.com/in/jamr2021/

format:
  html:
    theme: flatly
    toc: false
    page-layout: full
    css: styles.css
 